port: 8895

index_dbPath: /scratch/users/ntu/mohor001/raglab_final_embedding/datasets_PS
text_dbPath: /scratch/users/ntu/mohor001/raglab_final/datasets/programming_solutions_colbert.tsv
retriever_modelPath: /home/users/ntu/mohor001/col/colbertv2.0
