port: 8896

index_dbPath: /scratch/users/ntu/mohor001/raglab_final_embedding/datasets_lib
text_dbPath: /scratch/users/ntu/mohor001/raglab_final/datasets/library_documentation_colbert.tsv
retriever_modelPath: /home/users/ntu/mohor001/col/colbertv2.0
