port: 8893
index_dbPath: /home/wyd/zxw-github/RAGLAB/data/retrieval/colbertv2.0_embedding/wiki2023-10samples
text_dbPath: /home/wyd/zxw-github/RAGLAB/data/retrieval/colbertv2.0_passages/wiki2023-10samples/enwiki-20230401-10samples.tsv
retriever_modelPath: ./model/colbertv2.0